version: '3.8'

services: 
  java_app:
    container_name: monitoring_app
    image: monitoring-server:1.0
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ep-orange-mouse-a53dvofw-pooler.us-east-2.aws.neon.tech/monitoring_db?sslmode=require
      SPRING_DATASOURCE_USERNAME: monitoring_db_owner
      SPRING_DATASOURCE_PASSWORD: npg_0FDrhHGC5tgK
      SPRING_PROFILES_ACTIVE: docker
      VAADIN_PRODUCTION_MODE: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    volumes:
      - app_logs:/app/logs
    networks:
      - monitoring_network

networks:
  monitoring_network:
    driver: bridge

volumes:
  app_logs:
    name: monitoring_app_logs
